#!/usr/bin/env python

##########################################################################
# Project:
#   JobSub
#
# Author:
#   Parag Mhashilkar
#
# Description:
#   This module implements the JobSub client tool
#
##########################################################################

from __future__ import print_function
from __future__ import absolute_import
from __future__ import unicode_literals
from __future__ import division
from future import standard_library
standard_library.install_aliases()
import sys
import os
import argparse 
import traceback

import logSupport
from jobsubClient import JobSubClient
from jobsubClient import JobSubClientError
from jobsubClient import Version_String
from jobsubClient import http_code_to_rc
from jobsubClient import JID_Callback
from defaultServer import defaultServer


def print_opts(options):
    logSupport.dprint('COMMAND LINE OPTIONS:')
    logSupport.dprint('%s' % options)


def required_args_present(options):
    try:
        if options.acctGroup and options.jobsubServer and \
                (options.jobId or options.uid or options.constraint):
            return True
    except AttributeError:
        return False
    return False


def parse_opts(argv):
    usage = '%(prog)%s [Client Options]'
    epi_text = """REQUIRED arguments to hold jobs are (-G AND  (--jobid OR """
    epi_text += """--user OR --constraint) ).  Please direct questions, """
    epi_text += """comments, or problems to the service desk.  """
    epi_text += "For help on --jobid or --constraint see "
    epi_text += """https://cdcvs.fnal.gov/redmine/projects/"""
    epi_text += """jobsub/wiki/Frequently_Asked_Questions"""

    parser = argparse.ArgumentParser(usage=usage,
                                   conflict_handler="resolve",
                                   epilog=epi_text)

    client_options = parser.add_argument_group("Client Options")

    # Required args
    client_options.add_argument('-G', '--group',
                         dest='acctGroup',
                         type=str,
                         action='store',
                         metavar='<Group/Experiment/Subgroup>',
                         default=os.environ.get('JOBSUB_GROUP'),
                         help="".join(['Group/Experiment/Subgroup ',
                                       'for priorities and accounting',
                                      ]))

    # Optional args
    client_options.add_argument('--jobsub-server',
                         dest='jobsubServer',
                         action='store',
                         metavar='<JobSub Server>',
                         default=defaultServer(),
                         help='Alternate location of JobSub server to use')

    client_options.add_argument('--role',
                         dest='acctRole',
                         type=str,
                         action='store',
                         metavar='<VOMS Role>',
                         default=None,
                         help='VOMS Role for priorities and accounting')

    client_options.add_argument('--jobid',
                         dest='jobId',
                         type=str,
                         action=JID_Callback,
                         metavar='<Job ID>',
                         default=None,
                         help="".join(['CSV list of Job Ids to hold.  Job ',
                                       'Ids have format of ',
                                       '(cluster).(process)@(schedd_name). ',
                                       'If Job id has a decimal point but no ',
                                       'process ',
                                       '(example) 1234.@fifebatch.fnal.gov ',
                                       'then ALL job ids with that cluster ',
                                       'and schedd name will be removed',
                                      ]))
    client_options.add_argument('--debug',
                         dest='debug',
                         action='store_true',
                         default=False,
                         help="".join(['Print debug messages including ',
                                       'server contacted, http response, ',
                                       'response time',
                                      ]))

    client_options.add_argument('-h', '--help',
                         dest='help',
                         action='store_true',
                         default=False,
                         help='Show this help message and exit')

    client_options.add_argument('--user',
                         dest='uid',
                         type=str,
                         action='store',
                         default=None,
                         metavar='<user ID>',
                         help='hold all jobs with this uid ')

    client_options.add_argument('--constraint',
                         dest='constraint',
                         type=str,
                         action='store',
                         default=None,
                         metavar='<constraint>',
                         help='hold all jobs with this constraint ')

    client_options.add_argument('--version',
                        action=Version_String)

    if len(argv) < 1:
        print("ERROR: Insufficient arguments specified")
        parser.print_help()
        sys.exit(1)

    options, remainder = parser.parse_known_args(argv)

    if options.help or (len(remainder) > 1):
        parser.print_help()
        sys.exit(0)

    if not required_args_present(options):
        print("ERROR: Missing required arguments")
        print("%s" % parser.epilog)
        parser.print_help()
        sys.exit(1)
    return options


def main(argv):
    options = parse_opts(argv)
    logSupport.init_logging(options.debug)
    logSupport.dprint('CLIENT_ARGS: ', vars(options))
    extraOpts = {'debug': options.debug, 'uid': options.uid,
                 'constraint': options.constraint}
    js_client = JobSubClient(options.jobsubServer, options.acctGroup,
                             options.acctRole, None, extra_opts=extraOpts)
    rc = 1
    try:
        tmp_rc = 0

        if options.jobId:
            for jid in options.jobId.split(','):
                print('Holding job with jobid=%s' % jid)
                http_code = js_client.hold(jid,
                                           uid=options.uid,
                                           constraint=options.constraint)
                if isinstance(http_code, list):
                    for code in http_code:
                        tmp_rc += http_code_to_rc(code)
                else:
                    tmp_rc += http_code_to_rc(http_code)

            rc = tmp_rc
        else:
            if options.uid:
                print('Holding jobs owned by %s' % options.uid)
            if options.constraint:
                print('Holding jobs with constraint=%s' % options.constraint)
            http_code_list = js_client.hold(uid=options.uid,
                                            constraint=options.constraint)
            for http_code in http_code_list:
                tmp_rc = http_code_to_rc(http_code)
                if tmp_rc == 0:
                    rc = 0

    except JobSubClientError as e:
        print(e)
        logSupport.dprint(traceback.format_exc())
    except Exception as e:
        print(e)
        logSupport.dprint('%s' % traceback.print_exc())

    return rc


if __name__ == '__main__':
    sys.exit(main(sys.argv))
