#!/usr/bin/env python

################################################################################
# Project:
#   JobSub
#
# Author:
#   Parag Mhashilkar
#
# Description:
#   This module implements the JobSub client tool
#
################################################################################

import sys
import os
import getopt
import optparse
import time
import traceback

import constants
import logSupport
from jobsubClient import JobSubClient
from jobsubClient import JobSubClientError
from jobsubClient import version_string
from jobsubClient import http_code_to_rc
from defaultServer import defaultServer

def print_opts(options):
    logSupport.dprint('COMMAND LINE OPTIONS:')
    logSupport.dprint('%s' % options)


def required_args_present(options):
    try:
        if options.acctGroup and options.jobsubServer and options.jobId:
            return True
    except AttributeError:
        return False
    return False


def parse_opts(argv):
    usage = '%prog [Client Options]'
    parser = optparse.OptionParser(usage=usage,
                                   version=version_string(),
                                   conflict_handler="resolve",
                                   epilog="please direct questions comments, or problems to the service desk")

    opt_group = optparse.OptionGroup(parser, "Client Options")

    # Required args
    opt_group.add_option('-G', '--group',
                         dest='acctGroup',
                         type='string',
                         action='store',
                         metavar='<Group/Experiment/Subgroup>',
                         default=os.environ.get('JOBSUB_GROUP'),
                         help='Group/Experiment/Subgroup for priorities and accounting')

    # Optional args
    opt_group.add_option('--jobsub-server',
                         dest='jobsubServer',
                         action='store',
                         metavar='<JobSub Server>',
                         default=defaultServer(),
                         help='Alternate location of JobSub server to use')

    opt_group.add_option('--role',
                         dest='acctRole',
                         type='string',
                         action='store',
                         metavar='<VOMS Role>',
                         default=None,
                         help='VOMS Role for priorities and accounting')

    opt_group.add_option('--jobid',
                         dest='jobId',
                         type='string',
                         action='store',
                         metavar='<Job ID>',
                         help='CSV list of Job Ids to release')

    opt_group.add_option('--debug',
                         dest='debug',
                         action='store_true',
                         default=False,
                         help='Print debug messages including server contacted, http response, response time')

    opt_group.add_option('-h', '--help',
                         dest='help',
                         action='store_true',
                         default=False,
                         help='Show this help message and exit')



    parser.add_option_group(opt_group)

    if len(argv) < 1:
        print "ERROR: Insufficient arguments specified"
        parser.print_help()
        sys.exit(1)

    options, remainder = parser.parse_args(argv)

    if options.help or (len(remainder) > 1):
        parser.print_help()
        sys.exit(0)

    if not required_args_present(options):
        print "ERROR: Missing required arguments"
        parser.print_help()
        sys.exit(1)
    return options


def main(argv):
    options = parse_opts(argv)
    logSupport.init_logging(options.debug)
    logSupport.dprint('CLIENT_ARGS: ', options)
    js_client = JobSubClient(options.jobsubServer, options.acctGroup,
            options.acctRole, None, extra_opts={'debug':options.debug})
    rc = 1
    try:
        tmp_rc = 0
        for jid in options.jobId.split(','):
            print 'Releasing job with jobid=%s' % jid
            http_code = js_client.release(jid)
            tmp_rc += http_code_to_rc(http_code)
        rc = tmp_rc
    except JobSubClientError, e:
        print e
        logSupport.dprint(traceback.format_exc())
    except Exception, e:
        print e
        logSupport.dprint('%s' % traceback.print_exc())
    return rc

if __name__ == '__main__':
    sys.exit(main(sys.argv))
