#JOBSUB VERSION
VER=1.2.1
#RELEASE CANDIDATE NUMBER, COMMENT OUT IF FINAL RELEASE
RC=2
#JOBSUB_TOOLS MAJOR VERSION
TOOL_VER=v1_4
#JOBSUB_TOOLS MINOR VERSION
TOOL_MVER=6
#UNCOMMENT IF YOU WANT TO SEND RPM TO PRODUCTION REPO
#PROD=prod
#UNCOMMENT IF YOU WANT TO TAG VERSIONS AND PUSH THEM TO ORIGIN
#TAG_AND_PUSH=yes
#UNCOMMENT TO DO PRACTICE RUN - COMMANDS TO STDOUT INSTEAD OF EXECUTING THEM
PRACTICE_RUN=yes
#NODE TO SSH TO PACKAGE UPS/UPD PRODUCTS
UPSNODE=novagpvm01

