name: build-sl7-push

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  pushed_commit:
    runs-on: ubuntu-20.04
    name: "Build master after push in AL9 container"
    container:
      image: fermilab/fnal-wn-sl7
    steps:
      - name: Install glibc if needed
        run: yum info glibc || yum install -y glibc
      - name: Upgrade glibc
        run: yum upgrade glibc
      - name: Check out jobsub_lite in runner
        uses: actions/checkout@v4
      - name: Check out jobsub_lite_config in runner
        uses: actions/checkout@v4
        with:
          repository: fermitools/jobsub_lite_config
          path: config
          token: ${{ secrets.ACCESS_JOBSUB_LITE_CONFIG }}
      - uses: ./.github/actions/build-with-make-sl7
