name: build-al9-push

on:
  push:
    branches:
      - *
  workflow_dispatch:

jobs:
  pushed_commit:
    runs-on: ubuntu-latest
    name: "Build master after push in AL9 container"
    container:
      image: scientificlinux/sl:7
    steps:
      - name: Check out jobsub_lite in runner
        uses: actions/checkout@v4
      - name: Check out jobsub_lite_config in runner
        uses: actions/checkout@v4
        with:
          repository: fermitools/jobsub_lite_config
          path: config
          token: ${{ secrets.ACCESS_JOBSUB_LITE_CONFIG }}
      - uses: ./.github/actions/build-with-make-sl7
